### PR TITLE
Fixed description in text referring to http instead of html

### PR DESCRIPTION
**Pull request by hubbergit**

### CODE REVIEW

**Comment by hubbergit** [comment]
@HookyQR Can you please explain why you refused to merge my change proposal?

**Comment by HookyQR** [comment]
I don't accept merge request for typo updates. I appreciate you finding it though. If you'd like to submit a _code_ PR, that will likely be accepted.

**Comment by hubbergit** [comment]
Ok, thanks for that explaination!

However does this mean you will fix it yourself?

And does it mean I should ignore more typos or create new issues for them instead?

**Comment by HookyQR** [comment]
I'd be happy with an issue logged.

I've fixed it here, but I need to make some changes before I publish a new version as the fixes I made on `js-beautify` have now been released, so I can update the included version. Unfortunately I didn't push the changes up to github (oversight) and they're on a different machine so it will have to wait till I get home.

**Comment by hubbergit** [comment]
Understood! I will create issues for typos instead. I just thought it would be easier for you, if you just have to merge it, but creating an issue is absolutely fine for me.

Let me use this opportunity to thank you for this nice VS-Code extension.

**Pull request closed without merging**
