### PR TITLE
Fix issues#103

### PR DESCRIPTION
**Pull request by IgorNovozhilov**
Improvements on the issue #103

### CODE REVIEW

**Comment by IgorNovozhilov** [comment]
Not found examples of this functionality. Posted question: https://github.com/Microsoft/vscode/issues/20791

**Comment by HookyQR** [comment]
Me either. Doing a block copy now. Had to fix up some anomalies once I added tests.

**Comment by HookyQR** [comment]
Even that doesn't work.

**Comment by HookyQR** [comment]
New version pushed.

**Comment by IgorNovozhilov** [comment]
@HookyQR, read the answer to my question in vscode repo. Looks like I'll have to duplicate the options in the package.json.

**Comment by HookyQR** [comment]
Problem solved. Referencing version at [schema store](http://json.schemastore.org/jsbeautifyrc) for now. Once the PR on that repo is accepted, we'll switch to using the nested (and up to date) version.

**Pull request merged**
